import Link from "next/link"
import { Activity, ArrowRight, Cpu, Database, Globe2, Network, Server, ShieldCheck } from "lucide-react"
import Footer from "../components/Footer"
import Navbar from "../components/Navbar"
import { createPageMetadata } from "../seo"

export const metadata = createPageMetadata({ title: "India Cloud Infrastructure & Mumbai Hosting Network", description: "Explore Hostlixo India hardware profiles, Mumbai infrastructure, NVMe storage, network filtering and additional service regions.", path: "/infrastructure", keywords: ["Hostlixo India infrastructure", "Mumbai hosting nodes", "AMD EPYC™ 7763 hosting", "AMD Ryzen VPS India", "India hosting network"] })

const profiles = [
  { product: "Game hosting", cpu: "AMD EPYC™ 7763", memory: "Plan-based RAM", storage: "NVMe allocations", network: "DDoS-filtered" },
  { product: "Cloud VPS", cpu: "AMD Ryzen 7 / Ryzen 9", memory: "DDR5 plans", storage: "25–256 GB NVMe", network: "Plan bandwidth" },
  { product: "Dedicated cloud", cpu: "AMD Ryzen 7 / Ryzen 9", memory: "16–256 GB", storage: "500 GB–8 TB NVMe", network: "Plan-defined" },
  { product: "Web & bot hosting", cpu: "Shared or assigned vCPU", memory: "Plan-defined", storage: "SSD or NVMe", network: "Protected routing" },
]

const regions = [
  ["India", "Mumbai", "Primary region for Indian and South Asian audiences"], ["Singapore", "Singapore", "Southeast Asian audiences"], ["Germany", "Frankfurt", "European audiences"], ["USA", "California", "North American audiences"],
]

export default function InfrastructurePage() {
  return <div className="min-h-screen bg-[#07080d] text-white"><Navbar /><main className="pb-24 pt-28">
    <section className="relative overflow-hidden px-4 py-16 text-center sm:px-6 lg:px-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(156,163,175,.14),transparent_42%)]" /><div className="relative mx-auto max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[.24em] text-gray-300">Hostlixo infrastructure</p><h1 className="mt-4 text-4xl font-black sm:text-5xl">Hardware, regions and network design</h1><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-gray-400">Technical information for evaluating Hostlixo game hosting, VPS, dedicated cloud, web hosting and bot hosting before purchase.</p></div></section>

    <section className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><ArchitectureIllustration /><div className="rounded-2xl border border-white/10 bg-[#050505] p-6"><p className="text-[10px] font-black uppercase tracking-wider text-gray-300">Service path</p><h2 className="mt-2 text-2xl font-black">From visitor to workload</h2><div className="mt-6 space-y-3"><Layer icon={Globe2} title="Regional entry" text="Traffic enters through Mumbai or the selected Singapore, Germany or USA service region." /><Layer icon={ShieldCheck} title="Network filtering" text="Supported traffic passes through DDoS-filtered connectivity before reaching the service." /><Layer icon={Server} title="Assigned compute" text="The selected CPU, memory, storage and bandwidth allocation powers the workload." /><Layer icon={Activity} title="Monitoring and support" text="Infrastructure monitoring and service escalation operate around the clock." /></div></div></div></section>

    <section className="mx-auto mt-16 max-w-6xl px-4 sm:px-6 lg:px-8"><header><p className="text-[10px] font-black uppercase tracking-wider text-gray-300">Node specifications</p><h2 className="mt-2 text-3xl font-black">Hardware profiles by product</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-gray-400">Exact checkout resources take precedence. The table summarizes the profiles currently presented on Hostlixo product pages.</p></header><div className="mt-7 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[800px] text-left"><thead className="bg-[#10131a] text-[10px] uppercase tracking-wider text-gray-500"><tr>{["Product", "Processor", "Memory", "Storage", "Network"].map((head) => <th key={head} className="border-l border-white/[0.07] p-4 first:border-l-0">{head}</th>)}</tr></thead><tbody>{profiles.map((profile, index) => <tr key={profile.product} className={index % 2 ? "bg-white/[0.015]" : "bg-[#0a0c11]"}><th className="p-4 text-xs text-white">{profile.product}</th><td className="border-l border-white/[0.07] p-4 text-xs text-gray-400">{profile.cpu}</td><td className="border-l border-white/[0.07] p-4 text-xs text-gray-400">{profile.memory}</td><td className="border-l border-white/[0.07] p-4 text-xs text-gray-400">{profile.storage}</td><td className="border-l border-white/[0.07] p-4 text-xs text-gray-400">{profile.network}</td></tr>)}</tbody></table></div></section>

    <section className="mx-auto mt-16 max-w-6xl px-4 sm:px-6 lg:px-8"><header className="text-center"><p className="text-[10px] font-black uppercase tracking-wider text-gray-300">Regional network</p><h2 className="mt-2 text-3xl font-black">Four locations, one dashboard</h2></header><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{regions.map(([country, city, use]) => <article key={country} className="rounded-xl border border-white/10 bg-[#050505] p-5 transition hover:-translate-y-1 hover:border-white/35"><Globe2 className="h-5 w-5 text-gray-300" /><h3 className="mt-4 font-black">{country}</h3><p className="mt-1 text-xs text-gray-500">{city}</p><p className="mt-3 text-[11px] leading-5 text-gray-400">{use}</p></article>)}</div></section>

    <section className="mx-auto mt-16 max-w-6xl px-4 sm:px-6 lg:px-8"><div className="rounded-2xl border border-white/10 bg-[#050505] p-6 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-black uppercase tracking-wider text-gray-300">Verified node registry</p><h2 className="mt-2 text-3xl font-black">Public node disclosure standard</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-gray-400">Hostlixo should publish these fields for each production node after the operations team verifies the values. No example hardware is presented as live inventory.</p></div><span className="w-fit rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-[9px] font-black uppercase tracking-wider text-gray-300">Awaiting verified inventory</span></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Node ID and service role", "Exact CPU model", "Installed RAM and generation", "NVMe model and layout", "Committed uplink speed", "Datacenter provider", "City and country", "Monitoring status"].map((field) => <div key={field} className="rounded-lg border border-white/[0.07] bg-black/15 p-4 text-xs font-bold text-gray-300">{field}</div>)}</div><p className="mt-5 text-[10px] leading-5 text-gray-600">To publish nodes such as SG-01 or IN-01, provide the real inventory values and permission to disclose the datacenter relationship.</p></div></section>

    <section className="mx-auto mt-16 max-w-4xl px-4 sm:px-6"><div className="rounded-2xl border border-white/20 bg-white/[0.05] p-7 text-center"><h2 className="text-2xl font-black">Choose by workload, then test</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-gray-400">Use the disclosed resources to shortlist a service, select the closest region for your users, and measure the real application after deployment.</p><div className="mt-5 flex flex-wrap justify-center gap-3"><Link href="/benchmarks" className="rounded-lg border border-white/15 px-5 py-3 text-xs font-black">Benchmark methodology</Link><Link href="https://billing.hostlixo.com" className="inline-flex items-center gap-2 rounded-lg bg-gray-800 px-5 py-3 text-xs font-black">Open billing <ArrowRight className="h-4 w-4" /></Link></div></div></section>
  </main><Footer /></div>
}

function Layer({ icon: Icon, title, text }: { icon: typeof Server; title: string; text: string }) { return <div className="flex gap-3 rounded-xl border border-white/[0.07] bg-black/15 p-4"><span className="flex h-9 w-9 flex-none items-center justify-center rounded-lg bg-white/[0.04]"><Icon className="h-4 w-4 text-gray-300" /></span><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-[11px] leading-5 text-gray-500">{text}</p></div></div> }
function ArchitectureIllustration() { return <div className="relative min-h-[420px] overflow-hidden rounded-2xl border border-white/10 bg-[#0a0c12] p-6"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.04)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.04)_1px,transparent_1px)] [background-size:32px_32px]" /><div className="relative flex h-full flex-col justify-center"><p className="text-[10px] font-black uppercase tracking-wider text-gray-500">Original Hostlixo architecture illustration</p><div className="mt-8 grid grid-cols-2 gap-4"><Node icon={Network} label="Regional route" color="text-gray-300" /><Node icon={ShieldCheck} label="Filtering layer" color="text-gray-300" /><Node icon={Cpu} label="Compute node" color="text-gray-300" /><Node icon={Database} label="NVMe storage" color="text-gray-300" /></div><div className="mx-auto my-5 h-14 w-px bg-gradient-to-b from-gray-700 via-gray-500 to-gray-900" /><div className="mx-auto flex w-48 items-center justify-center gap-3 rounded-xl border border-white/20 bg-white/10 p-4"><Server className="h-5 w-5 text-gray-300" /><span className="text-xs font-black">Hosted workload</span></div></div></div> }
function Node({ icon: Icon, label, color }: { icon: typeof Cpu; label: string; color: string }) { return <div className="rounded-xl border border-white/10 bg-[#10131a] p-4 text-center"><Icon className={`mx-auto h-5 w-5 ${color}`} /><p className="mt-3 text-[11px] font-bold">{label}</p></div> }
