import Link from "next/link"
import { ArrowRight, Check, Cpu, Gauge, HardDrive, MapPin, ShieldCheck } from "lucide-react"
import Footer from "./Footer"
import Navbar from "./Navbar"

export default function IndiaHostingLanding({ type }: { type: "minecraft" | "vps" }) {
  const minecraft = type === "minecraft"
  const title = minecraft ? "Minecraft Hosting India" : "VPS Hosting India"
  const description = minecraft ? "Host Minecraft communities near Indian players with Mumbai region availability, plan-based RAM, NVMe storage and dashboard management." : "Deploy a Mumbai VPS with AMD Ryzen compute, NVMe storage, administrative access and transparent INR pricing."
  const href = minecraft ? "/games/minecraft" : "/vps"
  const specs = minecraft ? [["Starting plan", "2 GB RAM"], ["Compute", "AMD EPYC™ 7763"], ["Storage", "10 GB+ NVMe"], ["Price", "From ₹45/month"]] : [["Processor", "AMD Ryzen 7 / Ryzen 9"], ["Memory", "2–32 GB DDR5"], ["Storage", "25–256 GB NVMe"], ["Access", "Root / administrator"]]
  return <div className="min-h-screen bg-[#07080d] text-white"><Navbar /><main className="pb-24 pt-28"><section className="relative overflow-hidden px-4 py-16 sm:px-6 lg:px-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(156,163,175,.14),transparent_35%)]" /><div className="relative mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-gray-300">Mumbai region · INR pricing</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-8 text-gray-400">{description}</p><div className="mt-6 flex flex-wrap gap-3"><Link href={href} className="inline-flex items-center gap-2 rounded-lg bg-gray-800 px-5 py-3 text-sm font-black text-white">View plans <ArrowRight className="h-4 w-4" /></Link><Link href="/infrastructure" className="rounded-lg border border-white/15 px-5 py-3 text-sm font-black">Infrastructure</Link></div></div><div className="rounded-2xl border border-white/20 bg-[#0d0e14] p-6"><div className="flex items-center gap-3"><MapPin className="h-5 w-5 text-gray-300" /><div><p className="font-black">Mumbai, India</p><p className="text-xs text-gray-500">Asia South region</p></div></div><dl className="mt-6 grid grid-cols-2 gap-3">{specs.map(([label, value]) => <div key={label} className="rounded-xl border border-white/[0.07] bg-black/15 p-4"><dt className="text-[9px] uppercase tracking-wider text-gray-600">{label}</dt><dd className="mt-2 text-xs font-bold">{value}</dd></div>)}</dl></div></div></section>
      <section className="mx-auto max-w-6xl px-4 py-14 sm:px-6 lg:px-8"><header className="max-w-2xl"><p className="text-[10px] font-black uppercase tracking-wider text-gray-300">Choose with context</p><h2 className="mt-2 text-3xl font-black">What Indian hosting buyers should compare</h2></header><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Card icon={Gauge} title="Route quality" text="Test from the ISPs and cities used by your actual players or visitors." /><Card icon={Cpu} title="Assigned compute" text="Compare CPU allocation and processor family, not RAM alone." /><Card icon={HardDrive} title="Storage" text="NVMe can improve saves, backups and application response under load." /><Card icon={ShieldCheck} title="Protection scope" text="Review network filtering alongside software security and backups." /></div></section>
      <section className="mx-auto max-w-4xl px-4 sm:px-6"><div className="rounded-2xl border border-white/10 bg-[#050505] p-7"><h2 className="text-2xl font-black">Why choose a Mumbai region?</h2><p className="mt-4 text-sm leading-7 text-gray-400">A Mumbai location can reduce geographic distance for many Indian users, but latency still depends on ISP routing, peering and congestion. Use Hostlixo’s homepage RTT tool as a starting point, then test the deployed service from representative networks.</p><ul className="mt-5 grid gap-3 text-xs text-gray-300 sm:grid-cols-2">{["Transparent INR plan display", "Four-region expansion options", "Published refund conditions", "Hardware and benchmark guidance"].map((item) => <li key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-gray-300" />{item}</li>)}</ul></div></section>
    </main><Footer /></div>
}
function Card({ icon: Icon, title, text }: { icon: typeof Cpu; title: string; text: string }) { return <article className="rounded-xl border border-white/10 bg-[#050505] p-5"><Icon className="h-5 w-5 text-gray-300" /><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-[11px] leading-5 text-gray-500">{text}</p></article> }
