import type { Metadata } from "next"
import { notFound } from "next/navigation"
import Navbar from "../../components/Navbar"
import Footer from "../../components/Footer"
import { getKbArticle, kbArticles } from "../articles"

export function generateStaticParams() { return kbArticles.map(({ slug }) => ({ slug })) }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = getKbArticle(slug); if (!article) return {}; const url = `https://hostlixo.com/kb/${article.slug}`; return { title: `${article.title} | Hostlixo Knowledge Base`, description: article.description, alternates: { canonical: url }, openGraph: { title: article.title, description: article.description, url, type: "article" } } }
export default async function KnowledgeArticle({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const article = getKbArticle(slug); if (!article) notFound(); const schema = { "@context": "https://schema.org", "@type": "TechArticle", headline: article.title, description: article.description, dateModified: article.updated, author: { "@type": "Organization", name: "Hostlixo Cloud" }, publisher: { "@id": "https://hostlixo.com/#organization" }, mainEntityOfPage: `https://hostlixo.com/kb/${article.slug}` }; return <div className="min-h-screen bg-[#07080d] text-white"><Navbar /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><main className="mx-auto max-w-3xl px-4 pb-24 pt-32 sm:px-6"><p className="text-[10px] font-black uppercase tracking-[.22em] text-gray-300">{article.category} guide</p><h1 className="mt-3 text-4xl font-black leading-tight sm:text-5xl">{article.title}</h1><p className="mt-5 text-base leading-7 text-gray-400">{article.description}</p><p className="mt-3 text-xs text-gray-600">Last updated {article.updated}</p><ol className="mt-12 space-y-8">{article.steps.map(([heading, body], index) => <li key={heading} className="rounded-xl border border-white/10 bg-[#050505] p-6"><div className="flex gap-4"><span className="flex h-8 w-8 flex-none items-center justify-center rounded-full bg-white/15 text-xs font-black text-gray-300">{index + 1}</span><div><h2 className="text-xl font-black">{heading}</h2><p className="mt-3 text-sm leading-7 text-gray-300">{body}</p></div></div></li>)}</ol></main><Footer /></div> }
