import { BadgeCheck, MessageSquareQuote, ShieldCheck } from "lucide-react"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import VerifiedFeedbackSection from "../components/VerifiedFeedbackSection"
import { createPageMetadata } from "../seo"

export const metadata = createPageMetadata({ title: "Verified Customer Feedback", description: "Read Hostlixo Cloud customer feedback and learn how reviews are verified and moderated.", path: "/reviews", keywords: ["Hostlixo reviews", "Hostlixo customer feedback", "hosting reviews"] })

export default function ReviewsPage() { return <div className="min-h-screen bg-[#000000] text-white"><Navbar /><main className="pb-20 pt-28"><section className="relative overflow-hidden px-4 py-20 text-center"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(156,163,175,.14),transparent_48%)]" /><div className="relative mx-auto max-w-3xl"><MessageSquareQuote className="mx-auto h-7 w-7 text-gray-300" /><p className="mt-4 text-[10px] font-black uppercase tracking-[.24em] text-gray-300">Customer feedback</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Trust should be verifiable.</h1><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-gray-400">Feedback is presented with clear context. Hostlixo does not invent review counts, ratings or customer identities.</p></div></section><VerifiedFeedbackSection /><section className="mx-auto mt-8 grid max-w-5xl gap-4 px-4 md:grid-cols-3"><Policy icon={BadgeCheck} title="Verification first" text="Published feedback should be connected to a genuine customer interaction." /><Policy icon={ShieldCheck} title="No paid placement" text="Review prominence is not sold as an advertising product." /><Policy icon={MessageSquareQuote} title="Useful context" text="Service type and experience matter more than an unexplained star count." /></section></main><Footer /></div> }
function Policy({ icon: Icon, title, text }: { icon: typeof BadgeCheck; title: string; text: string }) { return <article className="rounded-xl border border-white/[0.08] bg-[#101019] p-5"><Icon className="h-5 w-5 text-gray-300" /><h2 className="mt-4 font-black">{title}</h2><p className="mt-2 text-xs leading-6 text-gray-500">{text}</p></article> }
