import Link from "next/link"
import { BookOpen, Search } from "lucide-react"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import { createPageMetadata } from "../seo"
import { kbArticles } from "./articles"

export const metadata = createPageMetadata({ title: "Hostlixo Knowledge Base", description: "Hostlixo guides for PaperMC, VPS deployment, game panel management, security, backups and hosting operations.", path: "/kb", keywords: ["Hostlixo knowledge base", "install PaperMC", "create VPS", "Pterodactyl panel guide"] })
export default function KnowledgeBasePage() { return <div className="min-h-screen bg-[#07080d] text-white"><Navbar /><main className="mx-auto max-w-6xl px-4 pb-24 pt-32 sm:px-6 lg:px-8"><header className="max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[.22em] text-gray-300">Knowledge base</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Operate your hosting with confidence</h1><p className="mt-5 text-sm leading-7 text-gray-400">Practical Hostlixo documentation for common game server, VPS and panel workflows.</p></header><div className="mt-8 flex items-center gap-3 rounded-xl border border-white/10 bg-[#050505] px-4 py-3 text-sm text-gray-500"><Search className="h-4 w-4" />Browse the guides below. Full-text search can be added as the library grows.</div><div className="mt-8 grid gap-4 md:grid-cols-3">{kbArticles.map((article) => <article key={article.slug} className="rounded-xl border border-white/10 bg-[#050505] p-6 transition hover:-translate-y-1 hover:border-white/30"><BookOpen className="h-5 w-5 text-gray-300" /><p className="mt-4 text-[9px] font-black uppercase tracking-wider text-gray-600">{article.category} · Updated {article.updated}</p><h2 className="mt-2 text-lg font-black">{article.title}</h2><p className="mt-3 text-xs leading-6 text-gray-400">{article.description}</p><Link href={`/kb/${article.slug}`} className="mt-5 inline-flex text-xs font-black text-gray-300">Read guide →</Link></article>)}</div></main><Footer /></div> }
