import type { Metadata } from "next"
import { notFound } from "next/navigation"
import Navbar from "../../components/Navbar"
import Footer from "../../components/Footer"
import { articles, getArticle } from "../articles"

export function generateStaticParams() { return articles.map(({ slug }) => ({ slug })) }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = getArticle(slug); if (!article) return {}; const url = `https://hostlixo.com/blog/${article.slug}`; return { title: article.title, description: article.description, alternates: { canonical: url }, openGraph: { title: article.title, description: article.description, type: "article", url, publishedTime: article.published } } }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const article = getArticle(slug); if (!article) notFound(); const schema = { "@context": "https://schema.org", "@type": "BlogPosting", headline: article.title, description: article.description, datePublished: article.published, dateModified: article.published, author: { "@type": "Organization", name: "Hostlixo Cloud" }, publisher: { "@id": "https://hostlixo.com/#organization" }, mainEntityOfPage: `https://hostlixo.com/blog/${article.slug}` }; return <div className="min-h-screen bg-[#000000] text-white"><Navbar /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><main className="mx-auto max-w-3xl px-4 pb-20 pt-32 sm:px-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gray-300">Hostlixo hosting guide</p><h1 className="mt-3 text-4xl font-black leading-tight sm:text-5xl">{article.title}</h1><p className="mt-5 text-base leading-7 text-gray-400">{article.description}</p><p className="mt-3 text-xs text-gray-600">Published {article.published}</p><div className="mt-12 space-y-10">{article.sections.map(([heading, body]) => <section key={heading}><h2 className="text-2xl font-bold">{heading}</h2><p className="mt-4 text-sm leading-8 text-gray-300">{body}</p></section>)}</div></main><Footer /></div> }
