import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import { Activity, Bell, Clock3, Globe2, LifeBuoy, ShieldCheck } from "lucide-react"

const regions = ["India · Mumbai (Primary)", "Singapore · Singapore", "Germany · Frankfurt", "USA · California"]

export default function StatusPage() {
  return <div className="min-h-screen bg-[#000000] text-white"><Navbar /><main className="mx-auto max-w-6xl px-4 pb-20 pt-32 sm:px-6 lg:px-8">
    <header className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gray-300">Public service transparency</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Hostlixo monitoring and uptime information</h1><p className="mt-5 text-sm leading-7 text-gray-400">Understand the published service target, regional monitoring scope, maintenance communication and incident support process.</p></header>
    <section className="mt-10 grid gap-4 sm:grid-cols-3"><Stat icon={Activity} value="99.9%" label="Published uptime target" detail="Not audited historical uptime" /><Stat icon={Clock3} value="≈43m 50s" label="30-day target allowance" detail="Mathematical target context" /><Stat icon={ShieldCheck} value="24/7" label="Infrastructure monitoring" detail="Support escalation coverage" /></section>
    <section className="mt-5 rounded-xl border border-white/20 bg-white/[0.05] p-6"><div className="flex items-start gap-4"><Activity className="mt-0.5 h-5 w-5 text-gray-300" /><div><h2 className="font-bold">Live account-specific status</h2><p className="mt-2 text-xs leading-6 text-gray-400">Sign in to the Hostlixo dashboard to review active services and open a support ticket. Hostlixo does not publish invented historical percentages on this page; verified incident history can be added when a dedicated monitoring feed is connected.</p><a href="https://control.hostlixo.com" className="mt-4 inline-flex text-xs font-bold text-gray-300">Open dashboard →</a></div></div></section>
    <div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{regions.map((region) => <article key={region} className="rounded-xl border border-white/[0.08] bg-[#0d0d14] p-5"><Globe2 className="h-4 w-4 text-gray-300" /><h2 className="mt-4 font-bold">{region}</h2><p className="mt-2 text-xs leading-6 text-gray-500">Infrastructure monitoring and support escalation for services deployed in this region.</p></article>)}</div>
    <div className="mt-5 grid gap-4 md:grid-cols-2"><article className="rounded-xl border border-white/[0.08] bg-[#101019] p-6"><Bell className="h-5 w-5 text-gray-300" /><h2 className="mt-4 font-bold">Maintenance communication</h2><p className="mt-2 text-xs leading-6 text-gray-400">Planned work and service-specific notices are communicated through account channels when applicable.</p></article><article className="rounded-xl border border-white/[0.08] bg-[#101019] p-6"><LifeBuoy className="h-5 w-5 text-gray-300" /><h2 className="mt-4 font-bold">Report an issue</h2><p className="mt-2 text-xs leading-6 text-gray-400">Include the service name, time, error details and recent changes in a support ticket for faster investigation.</p></article></div>
  </main><Footer /></div>
}
function Stat({ icon: Icon, value, label, detail }: { icon: typeof Activity; value: string; label: string; detail: string }) { return <article className="rounded-xl border border-white/[0.08] bg-[#101019] p-5"><Icon className="h-5 w-5 text-gray-300" /><p className="mt-4 text-2xl font-black">{value}</p><h2 className="mt-1 text-xs font-bold text-gray-300">{label}</h2><p className="mt-2 text-[10px] text-gray-600">{detail}</p></article> }
